---
title: "Assignment 8"
output: pdf_document
date: "2023-09-26"
---

```{r}
library(titanic)
library(tidyverse)
library(tidymodels)
library(mice) #package for imputation
library(VIM) #visualizing missingness
library(rpart) #for classification trees
library(rpart.plot) #for plotting trees
library(RColorBrewer) #better visualization of classification trees
library(rattle) #better visualization of classification trees
library(caret)
```

```{r}
heart = read_csv("heart_disease-1.csv")
head(heart)
```

```{r}
heart = heart %>% mutate(ChestPainType = as_factor(ChestPainType)) %>% 
  mutate(HeartDisease = as_factor(HeartDisease)) %>%
  mutate(HeartDisease = ifelse(HeartDisease == 0,"No", "Yes")) %>%
  mutate(RestingECG = as_factor(RestingECG)) %>% mutate(Sex = as_factor(Sex)) %>%
  mutate(ExerciseAngina = as_factor(ExerciseAngina)) %>% mutate(ST_Slope = as_factor(ST_Slope))
```

```{r}
set.seed(12345)
heart_split = initial_split(heart, prop = 0.70, strata = HeartDisease)
train = training(heart_split)
test = testing(heart_split)
```

```{r}
heart_recipe = recipe(HeartDisease ~., train) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree() %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

heart_fit = fit(heart_wflow, train)
```

```{r}
tree = heart_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree) 
```
```{r}
fancyRpartPlot(tree, tweak=1.5) #tweak makes the tree a little easier to read
```

```{r}
heart_fit$fit$fit$fit$cptable
```

```{r}
set.seed(123)
folds = vfold_cv(train, v = 5)
```

```{r}
heart_recipe = recipe(HeartDisease ~., train) %>%
  step_dummy(all_nominal(),-all_outcomes())

tree_model = decision_tree(cost_complexity = tune()) %>% 
  set_engine("rpart", model = TRUE) %>% #don't forget the model = TRUE flag
  set_mode("classification")

tree_grid = grid_regular(cost_complexity(),
                          levels = 25) #try 25 sensible values for cp

heart_wflow = 
  workflow() %>% 
  add_model(tree_model) %>% 
  add_recipe(heart_recipe)

tree_res = 
  heart_wflow %>% 
  tune_grid(
    resamples = folds,
    grid = tree_grid
    )

tree_res
```

```{r}
tree_res %>%
  collect_metrics() %>%
  ggplot(aes(cost_complexity, mean)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) 
```


```{r}
best_tree = tree_res %>%
  select_best("accuracy")

best_tree
```

```{r}
final_wf = 
  heart_wflow %>% 
  finalize_workflow(best_tree)
```

```{r}
final_fit = fit(final_wf, train)

tree = final_fit %>% 
  pull_workflow_fit() %>% 
  pluck("fit")

fancyRpartPlot(tree, tweak = 1.5) 
```


```{r}
treepred = predict(final_fit, train, type = "class")
head(treepred)
```

```{r}
confusionMatrix(treepred$.pred_class,as.factor(train$HeartDisease),positive="Yes") #predictions first then actual
```


```{r}
treepred_test = predict(final_fit, test, type = "class")
head(treepred_test)
```

Caret confusion matrix and accuracy, etc. calcs  
```{r}
confusionMatrix(treepred_test$.pred_class,as.factor(test$HeartDisease),positive="Yes") #predictions first then actual
```
```




