---
title: "Assignment4"
output: pdf_document
date: "2023-09-18"
---

```{r}
library(tidyverse)
library(lubridate)
library(tidymodels)
```

```{r}
bike = read_csv("bike_cleaned-4.csv")
head(bike)
```

```{r}
bike = bike %>% mutate(dteday = mdy(dteday))
```

```{r}
bike = bike %>% mutate_if(is.character, as_factor)
```

```{r}
bike = bike %>% mutate(hr = as_factor(hr))
```

```{r}
set.seed(1234)
bike_split = initial_split(bike, prop = 0.70, strata = count)
train = training(bike_split)
test = testing(bike_split)
```

```{r}
mod1 = lm(count ~ season + mnth + hr + holiday + weekday + temp + weathersit, train)
summary(mod1)
```

```{r}
predict_train = predict(mod1, new_data = train)
summary(predict_train)
```

```{r}
bike_recipe = recipe(count ~ season + mnth + hr + holiday + weekday + temp + weathersit, train)

lm_model = #give the model type a name 
  linear_reg() %>% #specify that we are doing linear regression
  set_engine("lm") #specify the specify type of linear tool we want to use 

lm_wflow = 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(bike_recipe)

lm_fit = fit(lm_wflow, train)
summary(lm_fit$fit$fit$fit)
```

```{r}
lm_fit %>% predict(test) %>% bind_cols(test) %>% metrics(truth = count, estimate = .pred)
```



